version: '3'

services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - ./requirements/nginx/conf/:/etc/nginx/http.d/
      - ./requirements/nginx/tools:/etc/nginx/ssl/
      - wp-volume:/var/www/
    restart: always
    networks:
      - inception
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_ROOT: ${DB_ROOT}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
    container_name: mariadb
    ports:
      - "3306:3306"
    volumes :
      - db-volume:/var/lib/mysql
    restart: always
    networks:
      - inception
  wordpress:
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_ROOT: ${DB_ROOT}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
    container_name: wordpress
    restart: always
    volumes:
      - wp-volume:/var/www
    networks:
      - inception

volumes:
  wp-volume:
    driver_opts:
      o:      bind
      type:   none
      device: /home/${USER}/data/wordpress
  db-volume:
    driver_opts:
      o:      bind
      type:   none
      device: /home/${USER}/data/mariadb

networks:
  inception:
      driver: bridge

